### ISSUE TITLE
Missing entry for blockheight 784211

### ISSUE THREAD

**Issue by sha2fiddy** [0xB10C/miningpool-observer#62]
The following block is missing entirely from miningpool.observer:
Blockheight 784211
Blockhash 00000000000000000001c20c14a52b5ae7c6ca385c58943c82ce8b0a76893b68

The url returns msg `Record not found`:
https://miningpool.observer/template-and-block/00000000000000000001c20c14a52b5ae7c6ca385c58943c82ce8b0a76893b68

The block was mined just a few seconds after the prev block 784210.  Is it possible that 784211 was mined before miningpool.observer's Bitcoin node knew about the prev block, and therefore it didn't have a new template?

If my assumption is correct, is this expected behavior?  I would humbly suggest that it might be better to display some data about the block, with a disclaimer that it didn't have time to create a template to compare against.  Thanks!

**Comment by 0xB10C** [comment]
> The block was mined just a few seconds after the prev block 784210. Is it possible that 784211 was mined before miningpool.observer's Bitcoin node knew about the prev block, and therefore it didn't have a new template?

Correct. This is expected behavior. I agree that this case could be handled better by showing a something more telling than `Record not found` but I don't think adding information about the block is necessary. miningpool-observer is not a block(chain) explorer. Linking to other blockchain explorers could be done. AFAIK only mempool-space shows template information and I don't know how they handle blocks where they don't have templates.

**Comment by sha2fiddy** [comment]
Got it, thanks for the explanation.  I originally started investigating this block because Mempool's "block health" feature showed it at 0% and I was looking for a point of comparison 😂.
